version: "3.7"

services:
  validator:
    image: ccrpt/creditcoin:latest
    container_name: creditcoin-node
    volumes:
      - type: volume
        source: creditcoin-data-volume
        target: /data
    expose:
      - ${local_port}
      - 9944
      - 9933
      - 9615
    ports:
      - ${local_port}:${local_port}
    entrypoint: |
        bash -c '/bin/creditcoin-node --validator \
          --name ${nodename} \
          --prometheus-external \
          --telemetry-url "wss://telemetry.polkadot.io/submit/ 0" \
          --bootnodes "/dns4/bootnode.creditcoin.network/tcp/30333/p2p/12D3KooWAEgDL126EUFxFfdQKiUhmx3BJPdszQHu9PsYsLCuavhb" "/dns4/bootnode2.creditcoin.network/tcp/30333/p2p/12D3KooWRubm6c4bViYyvTKnSjMicC35F1jZNrzt3MKC9Hev5vbG" "/dns4/bootnode3.creditcoin.network/tcp/30333/p2p/12D3KooWSdzZaqoDAncrQmMUi34Nr29TayCr4xPvqcJQc5J434tZ" \
          --public-addr "/dns4/${public_ipv4_address}/tcp/${external_port}" \
          --chain mainnet \
          --mining-key ${SS58Address} \
          --base-path /data \
          --port ${local_port}'

volumes:
  creditcoin-data-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${path_to_data}